name: run su6 checks
on:
  push:
    branches-ignore:
      - master
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.11'
      cache: 'pip' # caching pip dependencies
  - run: pip install su6
  - run: su6 all